[project]
name = "pdv"
version = "0.0.1"
description = ""
authors = [
    {name = "Gilderlan silva da cruz and Gilvan candido"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-jose[cryptography] (>=3.5.0,<4.0.0)"
]
packages = [
    { include = "src" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
fastapi = {extras = ["all"], version = "^0.116.1"}
sqlmodel = "^0.0.24"
python-dotenv = "^1.1.1"
passlib = "^1.7.4"
jwt = "^1.4.0"
pandas = "^2.3.1"
requests = "^2.32.4"
bcrypt = "^4.3.0"
black = "^25.1.0"
isort = "^6.0.1"
validate-docbr = "^1.11.1"

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
profile = "black"
